In [17]:
from gavs import *
import statsmodels.api as sm

spector_data = sm.datasets.spector.load()

X = spector_data.exog
y = spector_data.endog

temp = GA(X=X, y=y, mod=sm.OLS, max_iter=10, random_seed=1)


In [18]:
operator_list = [temp.select_from_fitness_rank, temp.random_mutate, temp.split_and_glue_population]
temp.select(operator_list)


(array([0, 1, 1]), 39.66775270274435)

In [6]:
np.any((temp.starting_population == 0).all(axis=1))

False

In [ ]:
for i in range(100):
    operator_list = [temp.select_from_fitness_rank, temp.random_mutate, temp.split_and_glue_population]
    temp.select(operator_list)


In [ ]:
m = temp.mod(y, temp.X.drop(columns=X.columns[np.array([0, 0, 1]) == 0], axis=1)).fit()

In [ ]:
np.any((temp.starting_population == 0).all(axis=1))

True

In [ ]:
temp.starting_population[2] = [0,0,0]

In [ ]:
temp.starting_population

array([[1, 1, 0],
       [0, 1, 1],
       [1, 2, 3],
       [0, 0, 1]])

In [ ]:
zero_rows_indices = np.where((temp.starting_population == 0).all(axis=1))[0]

In [ ]:
zero_rows_indices

array([2])

In [ ]:
temp.starting_population

array([[1, 1, 0],
       [0, 1, 1],
       [0, 0, 0],
       [0, 0, 1]])