In [1]:
from gavs import *
import statsmodels.api as sm

spector_data = sm.datasets.spector.load()

X = spector_data.exog
y = spector_data.endog

temp = GA(X=X, y=y, mod=sm.OLS, max_iter=10)


In [2]:
a = temp.initialize_pop()

In [3]:
sorted_sol = temp.calc_fit_sort_population(a)[0]

In [4]:
sorted_sol

array([[1, 0, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [18]:
temp.select_from_fitness_rank(sorted_sol)

[0.4 0.3 0.2 0.1]


array([[0, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [0, 1, 1]])

In [14]:
np.arange(4, 0)

array([], dtype=int64)

In [16]:
np.arange(4, 0, -1)

array([4, 3, 2, 1])

In [19]:
5 //2

2

In [20]:
def weighted_choice(population, weights):
    chosen_individual = np.random.choice(population, p=weights)
    return chosen_individual

# Example usage:
population = [1, 2, 3, 4, 5]
individual_probabilities = [0.1, 0.2, 0.3, 0.2, 0.2]

selected_individual = weighted_choice(population, individual_probabilities)
print(f"Selected individual: {selected_individual}")


Selected individual: 2


In [21]:
selected_individual

2

In [8]:
def weighted_choice_2d(population, weights, n):
    chosen_rows = np.random.choice(np.arange(len(population)), size=n, p=weights, replace=True)
    selected_individuals = population[chosen_rows]
    return selected_individuals

# Example usage:
population = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_probabilities = [0.1, 0.4, 0.5]

n = len(population)  # Choose n equal to the number of rows in the population

selected_rows = weighted_choice_2d(population, row_probabilities, n)
print(f"Selected rows:\n{selected_rows}")


Selected rows:
[[7 8 9]
 [4 5 6]
 [7 8 9]]


In [9]:
np.arange(len(population)

SyntaxError: unexpected EOF while parsing (1025546758.py, line 1)

In [12]:
np.arange(len(population))

array([0, 1, 2])